### PR TITLE
Expose Entity Registration Conversation Options

### PR DESCRIPTION
**Pull request by spelech**
## Proposed change

This deserializes the `options` and `conversation` fields from the entity registry.  I have limited data there (only Assist, no Alexa/GA), so I started with the field that was most relevant to my needs, but could easily be expanded if someone wants to provide a sample containing Alexa/Google Assistant settings.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist

- [X] The code change is tested and works locally.
- [X] Local tests pass. **Your PR cannot be merged unless tests pass**
- [X] The code compiles without warnings (code quality check)
- [X] Tests have been added to verify that the new code works.

If user exposed functionality or configuration are added/changed:

- [ ] Documentation added/updated for http://netdaemon.xtz

### CODE REVIEW

**Comment by spelech** [comment]
I can't seem to edit the labels now, but this should be an enhancement

**Comment by helto4real** [comment]
> I can't seem to edit the labels now, but this should be an enhancement

I fixed that but the CI still seem to fail. Please investigate.

**Comment by spelech** [comment]
Cleaned up the coverage and fixed the tests, should be good to go.

**Review by helto4real — APPROVED** [review]
Looks good, thank you for your effort!

**Pull request merged**
