### PR TITLE
Update GitHub workflow files

### PR DESCRIPTION
**Pull request by bakgaard**
## Breaking change

No breaking changes

## Proposed change

- Reenable `ci_analyze.yml` when merging into main
- Add GitHub Actions to `dependabot`
- Update all Actions to latest major version

## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] The code compiles without warnings (code quality check)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration are added/changed:

- [ ] Documentation added/updated for https://netdaemon.xyz

[Docs repository]: https://github.com/net-daemon/docs
[Developer documentation]: https://netdaemon.xyz/docs/developer/

### CODE REVIEW

**Comment by helto4real** [comment]
Thanks a lot!! Love these kinds of contributions. I will do a proper review tomorrow after work.

**Comment by bakgaard** [comment]
No rush.

It all comes down to getting rid of warning when building.

**Review by helto4real — APPROVED** [review]
Looks good, thanks for this!

**Review by helto4real — APPROVED** [review]

**Comment by helto4real** [comment]
@bakgaard please make sure the commits are signed for better security. I let this one pass for now since it was an easy review.
image

**Comment by bakgaard** [comment]
Odd, I thought it was.
I will fix it for future commits.

**Pull request merged**
