### PR TITLE
MeansImplicitUse for NetDaemonAppAttribute

### PR DESCRIPTION
**Pull request by DerJuulsn**
## Proposed change

Adds the JetBrains MeansImplicitUse to the NetDaemonAppAttribute.
Helps R# and Rider to mark classes as used if the NetDeamonAppAttribute is used

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

### CODE REVIEW

**Comment by FrankBakkerNl** [comment]
I like this idea, If I am not correct there is a similar attributes in a MS namespace somewhere, that should probably work with both jet brains ans MS IDE and we would not have to reference JB packages

**Comment by DerJuulsn** [comment]
I've added the needed code directly as an internal class as stated on this site: https://blog.jetbrains.com/dotnet/2018/05/03/what-are-jetbrains-annotations/

So we can get rid of the nuget dependency.

@FrankBakkerNl I couldn't find anything similar in the MS namespace. JetBrains normally provides info about such attributes. For example the PureAttribute: https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#PureAttribute

**Comment by FrankBakkerNl** [comment]
This is nice indeed, now Rider will no longer show my app classes in gray :-)
Because the jetbrains code is now included as internal, I don't see a problem like this, how about you @helto4real ?

**Comment by helto4real** [comment]
> This is nice indeed, now Rider will no longer show my app classes in gray :-) Because the jetbrains code is now included as internal, I don't see a problem like this, how about you @helto4real ?

Yea this is much better solution. I accept that. Good solution. Thanks!

**Review by helto4real — APPROVED** [review]

**Pull request merged**
