### PR TITLE
add yaml multilevel mapping

### PR DESCRIPTION
**Pull request by Zorgino**
## Breaking change

should not break anything

## Proposed change

add multilevel mapping to support objects nested two and more levels in yaml

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

### CODE REVIEW

**Comment by helto4real** [comment]
Thanks a lot for the PR, please add a test case too.

**Comment by FrankBakkerNl** [comment]
Just did a quick manual test on this with the config
```yaml
debug_app:
  class: NetDaemon.DevelopmentApps.apps.DebugApp.DebugApp
  root:
    child1: hello
    next: 
      child1: world
      next:
        child1: more
```

Witout this fix it did not return the whole structure, now it does. A unit test would still be nice ofcourse

**Review by FrankBakkerNl — APPROVED** [review]

**Comment by Zorgino** [comment]
@FrankBakkerNl , @helto4real , added tests

**Review by FrankBakkerNl — APPROVED** [review]

**Comment by Zorgino** [comment]
local tests pass though

**Comment by helto4real** [comment]
> @FrankBakkerNl , @helto4real , added tests

Thanks! Restarted the CI and CI tests was ok. We have problems with sonarcube right now. All looks great! Merging this one.

**Pull request merged**
